### ISSUE TITLE
[Question]: Where does one configure the elasticsearch connection?

### ISSUE THREAD

**Issue by seandavi** [barseghyanartur/graphene-elastic#25]
First, thanks for putting this library together. I'm working to get things up and running so that I might be able to contribute a bit. 

I have an elasticsearch server that has a hostname and requires basic auth. Where can I configure this with graphene-elastic? I'm used to configuring the es client and then `using` it with basic elasticsearch_dsl Search. 

I apologize if I have missed this in the docs and a quick scan of the code didn't point me to the right place.

**Comment by barseghyanartur** [comment]
@seandavi:

Look, you work with documents. Connection shall be defined there. See how it's done in the [example project](https://github.com/barseghyanartur/graphene-elastic/blob/master/examples/search_index/documents/post.py#L32).

**Comment by seandavi** [comment]
Thanks, @barseghyanartur. That is the line I had missed.
