### ISSUE TITLE
Specifying facets in query with FacetedSearchFilter does not limit aggs.

### ISSUE THREAD

**Issue by seandavi** [barseghyanartur/graphene-elastic#26]
Here is what I am seeing when I specify only one facet in the query:

```
query newQuery {
  document (first:1, facets: [published]){
    edges {
      node {
        id
        accession
      }
     	cursor
    }
    facets 
  }
}
```

and here is the return from that query that includes both of the available facets. 

```
"facets": {
        "center_name": {
          "doc_count": 215818,
          "aggs": {
            "doc_count_error_upper_bound": 0,
            "sum_other_doc_count": 32624,
            "buckets": [
...
            ]
          }
        },
        "published": {
          "doc_count": 215818,
          "aggs": {
            "buckets": [
...
            ]
          }
```

**Comment by barseghyanartur** [comment]
@seandavi:

Can it be that you marked `center_name` to be enabled by default?

**Comment by barseghyanartur** [comment]
For clarification, [here](https://graphene-elastic.readthedocs.io/en/latest/faceted_search_backend.html) the `tags` will appear in facets always, since they have been marked as `enabled`.

```python

            'tags': {
                'field': 'tags.raw',
                'enabled': True,  # Will appear in the list by default
                'global': True,
            },
```

All other facets shall be enabled by query, as you do with `published`.

**Comment by seandavi** [comment]
> @seandavi:
> 
> Can it be that you marked `center_name` to be enabled by default?

It could be.... Yes, that was it, thanks. 

Sorry for the noise. I appreciate you taking the time to answer so quickly.
