### ISSUE TITLE
[Question]: How does one do filtering on date fields?

### ISSUE THREAD

**Issue by seandavi** [barseghyanartur/graphene-elastic#27]
I'm interested in applying range and gt/lt filters on one or more date fields. It appears that those filters are hard-coded to be used with "Decimal" types. Do you have an approach in mind for doing so? I can probably map the dates to something like a unix timestamp, but that complicates input for filtering. 

If one wanted to add such functionality if it doesn't yet exist, where would you suggest starting, @barseghyanartur.

**Comment by barseghyanartur** [comment]
@seandavi 

It's gonna be an easy fix.

**Comment by seandavi** [comment]
Thx!

**Comment by barseghyanartur** [comment]
@seandavi:

Done in 0.6, read updated docs.
