### ISSUE TITLE
Support for complex bool queries

### ISSUE THREAD

**Issue by seandavi** [barseghyanartur/graphene-elastic#28]
@barseghyanartur, I took a look at the django-es stuff. They seem to rely on a set of conventions for bool queries (must, should). I had started to implement something different by constructing the root query to have a couple of self-relations. The class as implemented looked like this. Don't take this code too literally; I just want to show the concept of using self-reference with `and` and `or`. 

```python
class BaseFilter(graphene.InputObjectType):

    @classmethod
    def __init_subclass_with_meta__(cls, *args, **kwargs):
        super().__init_subclass_with_meta__(*args, **kwargs)
        field = graphene.InputField(graphene.List(graphene.NonNull(cls)))
        cls._meta.fields.update({'or': field,
                                 'and': field,
                                 'match': graphene.Argument(graphene.String, description='abc [stuff](https://cnn.com)'),
                                 'multi_match':field})

    class Meta:
        abstract = True
```

Here, `field` is pretty simple, but one could replace `field` with a list of filtering and searching backends. Facets, postfilter, etc. would remain at the "top level" since it doesn't make sense for them to be included in bool operations. 

If I *again* overlooked something in the docs, ignore this comment.

**Comment by barseghyanartur** [comment]
@seandavi:

It's a very good point. I was certainly planning to support OR and AND queries (something that I didn't manage that well in `django-elasticsearch-dsl-drf`). Especially that GraphQL syntax is so permissive. 

I'm certainly interested in good ideas and contributions. Could you push your code somewhere I could test it?

**Comment by seandavi** [comment]
I'll start working on a reproducible example. What will take some thought is about what can go inside bool and what cannot. Some filter backends can and some cannot. Also, ordering of backends probably matters, particularly once nesting is included.

**Comment by barseghyanartur** [comment]
Let's break it down.

Very roughly speaking, we have the following:

- Search backend
- Filter backend
- Ordering backend

When and where could AND and OR queries be handy?

Certainly in Search- and Filter-backends.

Search backend (in near future) will have [Simple query string](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/query-dsl-simple-query-string-query.html) supported. I wouldn't worry much about that.

What would be most handy, is a way to combine filters with AND and OR. Thus, Filter backend it is.

Does that make sense to you?

**Comment by barseghyanartur** [comment]
P. S. 

Last but not least - I plan to implement [Query string](https://www.elastic.co/guide/en/elasticsearch/reference/7.1/query-dsl-query-string-query.html) support as well.

**Comment by seandavi** [comment]
I think that anything that can go inside `Q` can end up inside AND and OR. https://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html#query-combination. Filter context can also go in here. And query string is just another type of query, so it would fit as well.

**Comment by barseghyanartur** [comment]
Update. Now that (simple) query string backends are implemented, complex queries are possible.

https://graphene-elastic.readthedocs.io/en/latest/query_string_backend.html
https://graphene-elastic.readthedocs.io/en/latest/simple_query_string_backend.html
