### ISSUE TITLE
[Question] First example throws RequestError

### ISSUE THREAD

**Issue by petroslamb** [barseghyanartur/graphene-elastic#31]
Hi, great job starting this lib.

I am trying out the library, created the virtualenv, setup all requirements, populated elasticsearch data, as explained, all from the script. 

After I start up the flask app example, the first query example in the documentation throws an error:

```
query PostsQuery {
  allPostDocuments(filter:{category:{value:"Elastic"}}) {
    edges {
      node {
        id
        title
        category
        content
        createdAt
        comments
      }
    }
  }
}
```
Response:

```
{
  "errors": [
    {
      "message": "RequestError(400, 'search_phase_execution_exception', 'No mapping found for [title.raw] in order to sort on')",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allPostDocuments"
      ]
    }
  ],
  "data": {
    "allPostDocuments": null
  }
}
```

Any hints?

**Comment by barseghyanartur** [comment]
Very strange, I don't get that error. Which version of Elasticsearch are you using? I'm using 7.x locally, but tests (on Travis) are executed against 6.x. Did you run your tests on cloned repository? Or defined documents yourself?

**Comment by petroslamb** [comment]
Hey, thanks for the quick response.

Elasticsearch version is 6.8, but not from your script, I was already using the project docker-elk. This is the only place I didn't use your scripts, so there might be something there. 

I cloned the repo from latest develop and used the example scripts to populate the documents.

Thanks

**Comment by barseghyanartur** [comment]
@petroslamb:

It shouldn't be an issue. I see that Travis uses [Elasticsearch 6.5.4](https://github.com/barseghyanartur/graphene-elastic/blob/master/.travis.yml#L18).

One thing you should pay attention to, is your `elasticsearch-py` and `elasticsearch-dsl-py` versions. They should be compatible with your Elasticsearch version.

**Comment by petroslamb** [comment]
@barseghyanartur you are absolutely right, the versions of `elasticsearch-dsl` and `elasticsearch` python dependencies where both 7.x, since I had must have installed all dependencies by using `dev.txt`.
