### ISSUE TITLE
[Question] How does one filter on nested document fields?

### ISSUE THREAD

**Issue by petroslamb** [barseghyanartur/graphene-elastic#33]
I was looking on how to filter on nested document fields, any idea on how to go about it?

**Comment by barseghyanartur** [comment]
@petroslamb:

It's not yet implemented in this package. You will have to make a custom backend for it and some tiny parts of the code, alongside proper Document definition.

However, you could use [these docs](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/nested_fields_usage_examples.html) and these code samples:

- [document definition 1](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/documents/city.py)
- [viewset definition 1](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/viewsets/city.py)

And certainly, the most advanced example for nested filtering:

- [custom backend](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/tests/test_filtering_nested.py)
- [corresponding tests](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/src/django_elasticsearch_dsl_drf/tests/test_filtering_nested.py)
- [viewset](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/viewsets/address/default.py)
- [document definition](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf/blob/master/examples/simple/search_indexes/documents/address.py)

If you come up with something useful (and reusable), do not hesitate to make a contribution. :)

**Comment by barseghyanartur** [comment]
@petroslamb:

P. S.

Just in case, if you have budget for external help (or willing to sponsor some features), mail me.

**Comment by petroslamb** [comment]
@barseghyanartur 

Sorry for not closing the ticket sooner!

Thank you for your swift and excellent reply, a GraphQL solution may be implemented later in the year after all and I will contact you if I can find a way to budget it.
