### ISSUE TITLE
Update Flask Graphql to include the latest graphiql version

### ISSUE THREAD

**Issue by datavistics** [barseghyanartur/graphene-elastic#39]
This issue https://github.com/graphql-python/flask-graphql/issues/75 references a pull request https://github.com/graphql-python/graphql-server/pull/49 that merged the most recent graphIql changes.

Can we update graphene-elastic to point to the latest flask-graphql?

Thanks!

**Comment by CarlosAmaral** [comment]
I second that!

**Comment by barseghyanartur** [comment]
FYI, Flask, Django and Responder apps are just example apps (nothing more). This package depends on graphql-python. However, reqs are updated. Enjoy.
