### ISSUE TITLE
[Question] Mutations and Subscriptions?

### ISSUE THREAD

**Issue by CarlosAmaral** [barseghyanartur/graphene-elastic#40]
Hi,

Thanks for creating this library. I was unable to find code examples of mutations or subscriptions. Is it possible to accomplish these operation with this library?

Thank you for your time.

**Comment by barseghyanartur** [comment]
Not yet and it's not on the roadmap either. What's your use case?

**Comment by CarlosAmaral** [comment]
I just want to do elasticsearch inserts/updates using mutations. Anyway, ended up implementing mutations using graphene. Thanks for the answer.
