### ISSUE TITLE
How to use a non-default elastic connection

### ISSUE THREAD

**Issue by datavistics** [barseghyanartur/graphene-elastic#41]
What is the best way to pass in a non-default elastic connection?
I have it under `current_app` or by key from `connections.get_connection(connection_id)`

**Comment by barseghyanartur** [comment]
@datavistics:

Check the [examples](https://github.com/barseghyanartur/graphene-elastic/blob/master/examples/search_index/documents/post.py). It's best defined on the elasticsearch-dsl documents side.
