### ISSUE TITLE
Refresh index before querying

### ISSUE THREAD

**Issue by CarlosAmaral** [barseghyanartur/graphene-elastic#43]
Hi @barseghyanartur ,

How do I make sure the index has been refreshed before querying? Often times, an update/save happens and I want to query right after but that collection will not come with the latest.

For reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html#docs-refresh

Thanks for your time.

**Comment by barseghyanartur** [comment]
Not relevant for this library, but you work with [elasticsearch-dsl](https://github.com/elastic/elasticsearch-dsl-py/) to update/save your ES data, you could provide a `refresh` (default is False).
