### ISSUE TITLE
Is it possible to combine graphene-elastic with graphene-django?

### ISSUE THREAD

**Issue by GrayTable** [barseghyanartur/graphene-elastic#45]
I'm working on a project that uses graphene-django and I'd like to add search functionality with graphene-elastic. Currently, most objects in my app(50+) are subclassing `DjangoObjectType`, ie:

```
class PostNode(DjangoObjectType):
    class Meta:
        model = Post
        interfaces = (graphene.Node,)
``` 

Elastic version could look something like this:
```
class PostElasticNode(ElasticsearchObjectType):
    class Meta:
        interfaces = (graphene.Node,)
        document = PostDocument

        filter_backends = [
            FilteringFilterBackend,
        ]

        filter_fields = {
            'title': {
                'field': 'title',
                'default_lookup': LOOKUP_FILTER_TERM,
            },
        }
```

So as far as I understand:
1. DjangoObjectType determines what fields a GraphQL object has by looking at `model = Post`
2. ElasticsearchObjectType does it by looking at `document = PostDocument`

I guess my question is - is there a way to somehow combine `ElasticsearchObjectType` and `DjangoObjectType`, so that the `ElasticsearchConnectionField` resolves query with `PostNode` type and uses `PostElasticNode` only to determine available filters?

Currently, as far as I understand, I'd have to rewrite all the existing nodes as ElasticsearchObjectTypes, create relevant elastic Documents, including relations. Is there an easier way to go about this issue?

**Comment by barseghyanartur** [comment]
I don't think so. It wouldn't be safe (as unique identifiers are crucial).

**Comment by GrayTable** [comment]
Ok, just wanted to make sure I'm not missing anything :+1:
