### ISSUE TITLE
Fiter several fields using OR 

### ISSUE THREAD

**Issue by dmalisani** [barseghyanartur/graphene-elastic#47]
I need to find records which fields description **OR** searchKeys contain SEARCHED_STRING 
```
{
  productsSearching(
    filter: {
      	description:{wildcard:"*SEARCHED_STRING*"},
        searchKeys:{wildcard:"*SEARCHED_STRING*"}
      	
    }

  ) {
    edges {
      node {
        id,
        description,
        ownCode,
        searchKeys
      }
    }
  }
}
```

but I only achieve **AND** results

**Comment by barseghyanartur** [comment]
Good question. Easiest way to achieve this now is to use [query string](https://graphene-elastic.readthedocs.io/en/latest/query_string_backend.html) or [simple query string](https://graphene-elastic.readthedocs.io/en/latest/simple_query_string_backend.html) backends.

See the updated documentation.

**Comment by dmalisani** [comment]
Yes, but I cannot use wildcard on these ways right?

**Comment by barseghyanartur** [comment]
@dmalisani:

Yes, you can.

```graphql
    query PostsQuery {
      allPostDocuments(
        queryString:"(title:*oint) OR (content:Whit*)"
      ) {
        edges {
          node {
            id
            title
            category
            content
            createdAt
            comments
          }
        }
      }
    }
```
