### ISSUE TITLE
Possibility to use the request object in Filter backends

### ISSUE THREAD

**Issue by andrijan** [barseghyanartur/graphene-elastic#53]
Hey, just found this project, looks really good!

While testing this out on my project (Which currently uses django-elasticsearch-dsl-drf) I wanted to pre-filter the queryset by only selecting the documents the user has access to. But to do that I would need the `request` object.

The filter backend in the django-elasticsearch-dsl-drf I currently use (and trying to replicate) looks like this:

```Python
def filter_queryset(self, request, queryset, view):
    return queryset.filter(
        E_Q(
            'nested',
            path='followers',
            query=E_Q(
                'match',
                followers__id=request.user.id
            )
        ) | E_Q(
            'nested',
            path='job.followers',
            query=E_Q('match', job__followers__id=request.user.id)
        )
    )
```

Any idea how I could solve it with your project?

**Comment by barseghyanartur** [comment]
@andrijan:

See the updated example project (the very minimal configuration to have authentication checks working):

- [Example schema definition](https://github.com/barseghyanartur/graphene-elastic/blob/master/examples/schema/post/connection.py#L13)
- [Updated connection field](https://github.com/barseghyanartur/graphene-elastic/blob/master/examples/schema/post/connection.py#L77)
- [And routes](https://github.com/barseghyanartur/graphene-elastic/blob/master/examples/apps/django_app/run.py#L51)

1. Create a Django user

```./scripts/run_django.sh runserver```

2. Run Elasticsearch

```docker-compose up```

3. Add some data to the Elasticsearch

```./scripts/populate_elasticsearch_data.sh```

4. Run the example project:

```./scripts/run_django.sh runserver```

5. Go to http://localhost:8000/admin/ and enter your credentials

6. Go to http://localhost:8000/graphql and type in the following query:

```graphql
query PostsQuery {
      postDocumentsForUser {
        edges {
          node {
            id
            title
            userId
          }
        }
      }
    }
```

P. S.

If you have more questions regarding this implementations, take an initiative to dive deeper into the subject (Django/GraphQL/Elasticsearch).
