### ISSUE TITLE
Question: Resolve data across indices

### ISSUE THREAD

**Issue by toschilling** [barseghyanartur/graphene-elastic#55]
Hi,
thank you for providing graphene-elastic with some examples of the usage. Nonetheless I have problems to understand the key concepts. To be more precise: I have my data organized in different elasticsearch indices (say, "persons" and "contributions"). The "links" in between are URIs referencing the "_id" of the linked entities. I want to use graphene-elastic to resolve these data parts in the backend and provide all the data in one request over graphQL. Here is an example:
``` python

# define document as the data is used in "persons" Index 
class PersonDoc(elasticsearch_dsl.Document):
    class Index:
        name = "persons"
    name = elasticsearch_dsl.Text()
    _id = elasticsearch_dsl.Text()        # this does not seem to work 
                                          # though as "_id" is a metaField

class Person(graphene_elastic.ElasticsearchObjectType):
    class Meta(object)
        document = PersonDoc
        interfaces = (graphene.Node, )

# define document used for index "contributions". Here there are
# links in the field "contributor" pointing to a person, e.g.
#     {"contributor": "https://example.com/person/12345678"}
# where '12345678' is the "_id" used in the persons index, so I
# would expect to somehow resolve this "contributor" field for the
# graphQL query
class ContribitionDoc(elasticsearch_dsl.Document):
    class Index:
        name = "contributions"
    # this works and simply resolves to the URI
    contributor = elasticsearch_dsl.Text()
    contributor_resolved = Person()
    def resolve_contributor_resolved(parent, info):
        # split "id" from parent.contributor URI
        person_id = parent.contributor.split("/")[-1]
        # query elasticsearch "persons" index for this document
        conn = elasticsearch_dsl.connections.get_connection()
        person_doc = conn.get("persons", person_id, doc_type="_doc", _source_includes=[name])["_source"]
        return person_doc


class Person(graphene_elastic.ElasticsearchObjectType):
    class Meta(object)
        document = ContributionDoc
        interfaces = (graphene.Node, )

```

Somehow this does not work out correctly. Can you point me in the right direction, please?
Thank you in advance!

**Comment by barseghyanartur** [comment]
@toschilling 

It's an uncommon patern in Elasticsearch though. You could better move towards nested fields. You don't have to give up one of the models, even. Both can stay, with some data duplication. What you will win is speed and simplicity.

If you still want to go on the way you go, could you publish a working, easily reproducable/installable example project on GitHub and share it with me? I could take a look.

**Comment by toschilling** [comment]
Thank you @barseghyanartur for the direct feedback concerning the uncommon pattern. We will think about the approach gathering the data within one index in nested fields. It might be worth avoiding trouble on the side of graphene.

I think we can close the issue for now an I reopen it again, if there are news form my side.
